apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-demo
  labels:
    app: nginx
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
      - key: "test"
        operator: "Equal"
        value: "true"
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 300m
            memory: 0.5Gi
          limits:
            cpu: 1000m
            memory: 1Gi
