apiVersion: v1
kind: Service
metadata:
  name: dynamodb-local
  labels:
    run: dynamodb-local
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    run: dynamodb-local
---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-local-admin
  labels:
    run: dynamodb-local-admin
spec:
  ports:
  - port: 80
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    run: dynamodb-local-admin