---
# API secrets
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: datadog-secret
      namespace: datadog
      labels:
        app: "datadog"
    type: Opaque
    data:
      api-key: "YzUyNzBiOGRkMTViOWRkYmQxMmI5MzlkZjA1MDQ2ODQ="

# Token base: wTr/\h8}dk"R?.Y+-ECt54A%6N=y32W|
  - apiVersion: v1
    kind: Secret
    metadata:
      name: datadog-auth-token
      namespace: datadog
    type: Opaque
    data:
      token: "d1RyL1xoOH1kayJSPy5ZKy1FQ3Q1NEElNk49eTMyV3wK"
