apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${GLOBAL_CLUSTER_NAME}
  region: ${GLOBAL_CLUSTER_REGION}

nodeGroups:
  - name: system
    labels:
      role: system
    instancesDistribution:
      instanceTypes:
        - "t3.small"
        - "t2.small"
    taints:
      system: "true:NoSchedule"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/role: system
      k8s.io/cluster-autoscaler/node-template/taint/system: "true:NoSchedule"
    minSize: 0
    maxSize: 8
    desiredCapacity: 1
    volumeSize: 100
    volumeType: gp2
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
    availabilityZones:
      - "${GLOBAL_CLUSTER_REGION}a"
      - "${GLOBAL_CLUSTER_REGION}b"
      - "${GLOBAL_CLUSTER_REGION}c"
