apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:6.8.5
        resources:
          limits:
            cpu: 3
            memory: '3Gi'
          requests:
            cpu: 3
            memory: '3Gi'
        env:
          - name: ELASTICSEARCH_HOSTS
            value: elasticsearch-kibana
        ports:
          - containerPort: 5601
      nodeSelector:
        role: elk-workers
      tolerations:
      - key: "elk"
        operator: "Equal"
        value: "true"