apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        rewrite name dynamodb-ui.fennec.io dynamodb-local-admin.dynamodb.svc.cluster.local
        rewrite name dynamodb.fennec.io dynamodb-local.dynamodb.svc.cluster.local
        rewrite name elasticsearch.fennec.io elasticsearch-master.elk.svc.cluster.local
        rewrite name grafana.fennec.io grafana.monitoring.svc.cluster.local
        rewrite name grafana.fennec.io grafana.monitoring.svc.cluster.local
        rewrite name grafana.fennec.io grafana.monitoring.svc.cluster.local
        rewrite name grafana.fennec.io grafana.monitoring.svc.cluster.local
        rewrite name prometheus.fennec.io prometheus.monitoring.svc.cluster.local
        rewrite name alertmanager.fennec.io prometheus-alertmanager.monitoring.svc.cluster.local
        rewrite name fennec.ai fennec.ai
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    health\n    rewrite name dynamodb-ui.fennec.io dynamodb-local-admin.dynamodb.svc.cluster.local\n    rewrite name dynamodb.fennec.io dynamodb-local.dynamodb.svc.cluster.local\n    rewrite name elasticsearch.fennec.io elasticsearch-master.elk.svc.cluster.local\n    rewrite name grafana.fennec.io grafana.monitoring.svc.cluster.local\n    rewrite name grafana.fennec.io grafana.monitoring.svc.cluster.local\n    rewrite name grafana.fennec.io grafana.monitoring.svc.cluster.local\n    rewrite name grafana.fennec.io grafana.monitoring.svc.cluster.local\n    rewrite name prometheus.fennec.io prometheus.monitoring.svc.cluster.local\n    rewrite name fennec.ai fennec.ai\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n      pods insecure\n      upstream\n      fallthrough in-addr.arpa ip6.arpa\n    }\n    prometheus :9153\n    forward . /etc/resolv.conf\n    cache 30\n    loop\n    reload\n    loadbalance\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2020-07-18T07:42:20Z","labels":{"eks.amazonaws.com/component":"coredns","k8s-app":"kube-dns"},"name":"coredns","namespace":"kube-system","resourceVersion":"5272946","selfLink":"/api/v1/namespaces/kube-system/configmaps/coredns","uid":"958e525a-ecea-4218-9bc2-606425d4723a"}}
  creationTimestamp: "2020-07-18T07:42:20Z"
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system
  resourceVersion: "5392486"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: 958e525a-ecea-4218-9bc2-606425d4723a
