---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  selector:
    matchLabels:
      run: kafka-ui
  replicas: 1
  template:
    metadata:
      labels:
        run: kafka-ui
    spec:
      tolerations:
       - key: "kafka"
         operator: "Equal"
         value: "true"
         effect: "NoSchedule"
      containers:
      - name: kafkaui
        image: obsidiandynamics/kafdrop
        ports:
          - containerPort: 9000
        env:
          - name: JVM_OPTS
            value: "-Xms32M -Xmx64M"
          - name: SERVER_SERVLET_CONTEXTPATH
            value: "/"
          - name: KAFKA_BROKERCONNECT
            value: "zookeeper.example.com:2181,kafka.example.com:9092"
      nodeSelector:
        role: kafka-workers
