controller:
  kind: DaemonSet
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  tolerations:
  - key: "system"
    operator: "Equal"
    value: "true"
  - key: "redis"
    operator: "Equal"
    value: "true"
  - key: "elk"
    operator: "Equal"
    value: "true"
  - key: "jenkins"
    operator: "Equal"
    value: "true"
  - key: "kafka"
    operator: "Equal"
    value: "true"
  - key: "mongo"
    operator: "Equal"
    value: "true"
  - key: "vpn"
    operator: "Equal"
    value: "true"
  - key: "monitoring"
    operator: "Equal"
    value: "true"
  - key: "build"
    operator: "Equal"
    value: "true"
  - key: "gated"
    operator: "Equal"
    value: "true"