apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        rewrite name dashboard.fennec.ai internal-a5433d78c8cdd475abf031a0bd7cc120-464115148.eu-west-2.elb.amazonaws.com
        rewrite name fennec.ai fennec.ai
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system
