apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        rewrite name fennec.io fennec.io
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }