apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        rewrite name kibana.${CLUSTER_DOMAIN} kibana.kibana.svc.cluster.local
        rewrite name elasticsearch.${CLUSTER_DOMAIN} elasticsearch-master.elasticsearch.svc.cluster.local
        rewrite name elasticsearch-kibana.${CLUSTER_DOMAIN} elasticsearch-kibana.elasticsearch.svc.cluster.local
        rewrite name dashboard.${CLUSTER_DOMAIN} adf93856153ff4974a74f7bed661abdf-983ca521ddec1a16.elb.eu-west-1.amazonaws.com
        rewrite name grafana.${CLUSTER_DOMAIN} grafana.grafana.svc.cluster.local
        rewrite name prometheus-server.${CLUSTER_DOMAIN} prometheus-server.prometheus.svc.cluster.local
        rewrite name prometheus-alert.${CLUSTER_DOMAIN} prometheus-alertmanager.prometheus.svc.cluster.local
        rewrite name kafka-ui.${CLUSTER_DOMAIN} kafka-ui.kafka.svc.cluster.local
        rewrite name kafka.${CLUSTER_DOMAIN} kafka-cp-kafka.kafka.svc.cluster.local
        rewrite name zookeeper.${CLUSTER_DOMAIN} kafka-cp-zookeeper.kafka.svc.cluster.local
        rewrite name zookeepr.${CLUSTER_DOMAIN} kafka-cp-zookeeper.kafka.svc.cluster.local
        rewrite name redis-ui.${CLUSTER_DOMAIN} redis-ui.redis.svc.cluster.local
        rewrite name redis.${CLUSTER_DOMAIN} redis-master.redis.svc.cluster.local
        rewrite name redis-slave.${CLUSTER_DOMAIN} redis-slave.redis.svc.cluster.local
        rewrite name kafka-zookeeper.${CLUSTER_DOMAIN} kafka.kafka-zookeeper.svc.cluster.local
        rewrite name dynamodb.${CLUSTER_DOMAIN} dynamodb-local.dynamodb.svc.cluster.local
        rewrite name dynamodb-ui.${CLUSTER_DOMAIN} dynamodb-local-admin.dynamodb.svc.cluster.local
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }