cp-kafka:
  resources:
    limits:
      cpu: 3
      memory: 12Gi
    requests:
      cpu: 3
      memory: 3Gi
  imageTag: 5.3.1
  enabled: true
  brokers: 6
  tolerations:
  - key: "kafka"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  nodeSelector:
    role: kafka-workers
  persistence:
    enabled: true
    dataDirSize: 1000Gi
    dataLogDirSize: 5Gi
cp-zookeeper:
  imageTag: 5.3.1
  enabled: true
  tolerations:
  - key: "kafka"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  nodeSelector:
    role: kafka-workers
  servers: 6
  persistence:
    enabled: true
    dataDirSize: 1000Gi
    dataLogDirSize: 5Gi



    
cp-control-center:
  enabled: false
  tolerations:
  - key: "kafka"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  nodeSelector:
    role: kafka-workers
  persistence:
    enabled: true
    dataDirSize: 5Gi
    dataLogDirSize: 5Gi
cp-schema-registry:
  enabled: false
  tolerations:
  - key: "kafka"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  nodeSelector:
    role: kafka-workers
  persistence:
    enabled: true
    dataDirSize: 5Gi
    dataLogDirSize: 5Gi
cp-ksql-server:
  enabled: false
  tolerations:
  - key: "kafka"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  nodeSelector:
    role: kafka-workers
  persistence:
    enabled: true
    dataDirSize: 5Gi
    dataLogDirSize: 5Gi
cp-kafka-connect:
  enabled: false
  tolerations:
  - key: "kafka"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  persistence:
    enabled: true
    dataDirSize: 5Gi
    dataLogDirSize: 5Gi
  nodeSelector:
    role: kafka-workers
cp-schema-registry:
  enabled: false
  tolerations:
  - key: "kafka"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  persistence:
    enabled: true
    dataDirSize: 5Gi
    dataLogDirSize: 5Gi
  nodeSelector:
    role: kafka-workers
cp-kafka-rest:
  enabled: false
  tolerations:
  - key: "kafka"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  persistence:
    enabled: true
    dataDirSize: 5Gi
    dataLogDirSize: 5Gi
  nodeSelector:
    role: kafka-workers